---
name: check-commit
on: [push, pull_request]

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: jq '.' versions.json
